//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isa.Flow.EsIndexer.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Isa.Flow.EsIndexer.Resources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не задано имя очереди статей для индексации..
        /// </summary>
        internal static string ArticlesQueueNotDefined {
            get {
                return ResourceManager.GetString("ArticlesQueueNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не задано имя очереди статей для удаления..
        /// </summary>
        internal static string DeleteQueueNotDefined {
            get {
                return ResourceManager.GetString("DeleteQueueNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В конфигурационном файле не указан префикс индексов ES (параметр: ElasticSearch.IndexPrefix)..
        /// </summary>
        internal static string ESIndexPrefixNotSpecifiedError {
            get {
                return ResourceManager.GetString("ESIndexPrefixNotSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В конфигурационном файле не указаны адреса кластера ES (параметр: ElasticSearch.Hosts)..
        /// </summary>
        internal static string ESIndexUrlsNotSpecifiedError {
            get {
                return ResourceManager.GetString("ESIndexUrlsNotSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения файла параметров запуска..
        /// </summary>
        internal static string FuncParamsFileReadError {
            get {
                return ResourceManager.GetString("FuncParamsFileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при сохранении параметров запуска в файле..
        /// </summary>
        internal static string FuncParamsFileSaveError {
            get {
                return ResourceManager.GetString("FuncParamsFileSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при запуске функций индексатора..
        /// </summary>
        internal static string FuncStartError {
            get {
                return ResourceManager.GetString("FuncStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка в процессе индексации..
        /// </summary>
        internal static string IndexingError {
            get {
                return ResourceManager.GetString("IndexingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при запуске приложения..
        /// </summary>
        internal static string StartError {
            get {
                return ResourceManager.GetString("StartError", resourceCulture);
            }
        }
    }
}
