//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isa.Flow.SQLExtractor.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Isa.Flow.SQLExtractor.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Актор готов (ID: {0}).          .
        /// </summary>
        internal static string ActorInitialized {
            get {
                return ResourceManager.GetString("ActorInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инициализация актора....
        /// </summary>
        internal static string ActorInitializing {
            get {
                return ResourceManager.GetString("ActorInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистка уже запущена..
        /// </summary>
        internal static string CleanAlreadyStarted {
            get {
                return ResourceManager.GetString("CleanAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистка запущена с {0} по {1}..
        /// </summary>
        internal static string CleanStarted {
            get {
                return ResourceManager.GetString("CleanStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистка закончена..
        /// </summary>
        internal static string CleanStopped {
            get {
                return ResourceManager.GetString("CleanStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистка прервана из-за ошибки..
        /// </summary>
        internal static string CleanStoppedWithError {
            get {
                return ResourceManager.GetString("CleanStoppedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Извлечено статей для очистки: {0}; диапазон ID: {1} ... {2}.
        /// </summary>
        internal static string Cleared {
            get {
                return ResourceManager.GetString("Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл конфигурации прочитан..
        /// </summary>
        internal static string ConfigRead {
            get {
                return ResourceManager.GetString("ConfigRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установлены параметры запуска по умолчанию..
        /// </summary>
        internal static string DefaultFuncParamsSet {
            get {
                return ResourceManager.GetString("DefaultFuncParamsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция извлечения удаленных статей запущена..
        /// </summary>
        internal static string DeletedArticlesFuncStarted {
            get {
                return ResourceManager.GetString("DeletedArticlesFuncStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка запуска функции извлечения удаленных статей..
        /// </summary>
        internal static string DeletedArticlesFuncStartError {
            get {
                return ResourceManager.GetString("DeletedArticlesFuncStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция извлечения удаленных статей остановлена..
        /// </summary>
        internal static string DeletedArticlesFuncStopped {
            get {
                return ResourceManager.GetString("DeletedArticlesFuncStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция извлечения удаленных статей остановлена из-за ошибки..
        /// </summary>
        internal static string DeletedArticlesFuncStoppedWithError {
            get {
                return ResourceManager.GetString("DeletedArticlesFuncStoppedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Извлечено удаленных статей: {0}; диапазон ID: {1} ... {2}.
        /// </summary>
        internal static string DeletedExtracted {
            get {
                return ResourceManager.GetString("DeletedExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выхода введите &apos;exit&apos; или &apos;quit&apos;..
        /// </summary>
        internal static string ExitPrompt {
            get {
                return ResourceManager.GetString("ExitPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неудачная попытка чтения статей из БД. Причина: {0}.
        /// </summary>
        internal static string FailedReadingArticlesAttempt {
            get {
                return ResourceManager.GetString("FailedReadingArticlesAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неудачная попытка отправки статьи в очередь. Причина: {0}.
        /// </summary>
        internal static string FailedSendingArticleAttempt {
            get {
                return ResourceManager.GetString("FailedSendingArticleAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл параметров запуска прочитан..
        /// </summary>
        internal static string FuncParamsFileRead {
            get {
                return ResourceManager.GetString("FuncParamsFileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения файла параметров запуска..
        /// </summary>
        internal static string FuncParamsFileReadError {
            get {
                return ResourceManager.GetString("FuncParamsFileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка записи параметров запуска в файл..
        /// </summary>
        internal static string FuncParamsFileSaveError {
            get {
                return ResourceManager.GetString("FuncParamsFileSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логирование настроено..
        /// </summary>
        internal static string LoggingConfigured {
            get {
                return ResourceManager.GetString("LoggingConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция извлечения новых статей запущена..
        /// </summary>
        internal static string NewArticlesFuncStarted {
            get {
                return ResourceManager.GetString("NewArticlesFuncStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка запуска функции извлечения новых статей..
        /// </summary>
        internal static string NewArticlesFuncStartError {
            get {
                return ResourceManager.GetString("NewArticlesFuncStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция извлечения новых статей остановлена..
        /// </summary>
        internal static string NewArticlesFuncStopped {
            get {
                return ResourceManager.GetString("NewArticlesFuncStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция извлечения новых статей остановлена из-за ошибки..
        /// </summary>
        internal static string NewArticlesFuncStoppedWithError {
            get {
                return ResourceManager.GetString("NewArticlesFuncStoppedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Извлечено новых статей: {0}; диапазон ID: {1} ... {2}.
        /// </summary>
        internal static string NewExtracted {
            get {
                return ResourceManager.GetString("NewExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя очереди RabbitMQ не указано..
        /// </summary>
        internal static string QueueNameNotDefined {
            get {
                return ResourceManager.GetString("QueueNameNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реиндексация уже запущена..
        /// </summary>
        internal static string ReindexAlreadyStarted {
            get {
                return ResourceManager.GetString("ReindexAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Извлечено статей для реиндексации: {0}; диапазон ID: {1} ... {2}.
        /// </summary>
        internal static string Reindexed {
            get {
                return ResourceManager.GetString("Reindexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реиндексация запущена с {0} по {1}..
        /// </summary>
        internal static string ReindexStarted {
            get {
                return ResourceManager.GetString("ReindexStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реиндексация закончена..
        /// </summary>
        internal static string ReindexStopped {
            get {
                return ResourceManager.GetString("ReindexStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реиндексация прервана из-за ошибки..
        /// </summary>
        internal static string ReindexStoppedWithError {
            get {
                return ResourceManager.GetString("ReindexStoppedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при запуске приложения..
        /// </summary>
        internal static string StartError {
            get {
                return ResourceManager.GetString("StartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция извлечения измененных статей запущена..
        /// </summary>
        internal static string UpdatedArticlesFuncStarted {
            get {
                return ResourceManager.GetString("UpdatedArticlesFuncStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка запуска функции извлечения измененных статей..
        /// </summary>
        internal static string UpdatedArticlesFuncStartError {
            get {
                return ResourceManager.GetString("UpdatedArticlesFuncStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция извлечения измененных статей остановлена..
        /// </summary>
        internal static string UpdatedArticlesFuncStopped {
            get {
                return ResourceManager.GetString("UpdatedArticlesFuncStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция извлечения измененных статей остановлена из-за ошибки..
        /// </summary>
        internal static string UpdatedArticlesFuncStoppedWithError {
            get {
                return ResourceManager.GetString("UpdatedArticlesFuncStoppedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Извлечено измененных статей: {0}; диапазон ID: {1} ... {2}.
        /// </summary>
        internal static string UpdatedExtracted {
            get {
                return ResourceManager.GetString("UpdatedExtracted", resourceCulture);
            }
        }
    }
}
